### ISSUE TITLE
average speed is in kmh instead of mph

### ISSUE THREAD

**Issue by scabaa** [jordanmalecki/onemap#1]
I think you missing a conversion for the averageSpeed as it seems to be in kmh meanwhile all the other values converted to imperial

**Comment by jordanmalecki** [comment]
good catch
should be fixed with 63018a5ed4466329bf85ddb7abab0d0d4a494fa0

**Comment by jordanmalecki** [comment]
good catch
should be fixed with 63018a5ed4466329bf85ddb7abab0d0d4a494fa0

**Comment by jordanmalecki** [comment]
I fixed a few things in the dashboard that I never pushed (I.E. "ride efficieny" was a dup of the averageSpeed distribution) so I fixed it and included it in that push. Thanks for pointing out and for the pull req.
