### ISSUE TITLE
missing modules and some other readme/config.json notes

### ISSUE THREAD

**Issue by scabaa** [jordanmalecki/onemap#5]
Hey,
so running with the current changes up till [216d35c](https://github.com/jordanmalecki/onemap/commit/216d35c5d2913f0a5009ae816d5c06f50663355a) will yield in some missing modules errors.
I believe calmap is missing from requirements.txt (although mentioned in readme.txt Python requirements) and once I've added that it was the calmap module complained that it's missing distutils which it seems has been removed from Python 3.12.
Although it's still possible to use that if I am adding setuptools module in requirements.txt

With these two added, run.py is happy.

Another note is that in readme.txt you mentioning that at the fist run it will ask for the username/location/distance but since config.json is prefilled with those, it will be used. I assume you need to blank those config parameters.

Another thing I've seen is that in readme.txt the git clone command is mentioned with a different repo which is 19 commits behind now (i.e https://github.com/whoalacoasta/onemap)

Thanks for your efforts on this and sorry that I am not opening a merge request but I assume these are easy to be added in the way you see the best.

**Comment by jordanmalecki** [comment]
No don't be sorry. I shat out some major changes extremely fast. It'd be impossible for me to catch everything. I really appreciate you pointing these things out. Gonna dig into these now 🤗

**Comment by jordanmalecki** [comment]
Oh yeah. These were easy... i think. 
Really just needed to add the config.json to the .gitignore.

Lol let me know if I am mistaken and we need to reopen.

**Comment by scabaa** [comment]
It's all good! Working as expected! Thanks for the quick fix :)
